version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: notifications_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservices

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - microservices
    depends_on:
      - redis

  bullboard:
    image: deadly0/bull-board:latest
    container_name: bull_board
    restart: always
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - microservices
    depends_on:
      - redis

networks:
  microservices:
    driver: bridge